### PR TITLE
Integrate with machine learning library [4-8h] #4

### PR DESCRIPTION
**Pull request by sladomic**
Add activity for drawing numbers [8-16h] #13

### CODE REVIEW

**Comment by sladomic** [comment]
@jogrimst this is the first version with the TensorFlow model
1. The model I use here is not perfectly trained, so the accuracy will be better in the end
2. I uncommented the FinalActivity, so you get a Toast to check, which number has been detected
3. The model is included as an asset and therefore no need to copy it to the sdcard
4. This is only a SNAPSHOT version :)

**Comment by jogrimst** [comment]
@sladomic I was not able to compile and test the app.

**Comment by sladomic** [comment]
@jogrimst  please check again

**Review by jo-elimu — CHANGES_REQUESTED** [review]
@sladomic Can you move this pull request to https://github.com/literacyapp-org/literacyapp-handwriting-numbers?

**Comment by sladomic** [comment]
@jogrimst I think I'll open a new pull request but not before Thursday. One for here and one fore numeracy

**Pull request closed without merging**
